const dataInformes = {
    "ALERGIAS": {
        presentacion: "Se trata de paciente sin antecedentes mórbidos, el cual se encontraba asintomático hasta el día de ayer, cuando empezó a presentar prurito intenso generalizado, lesiones eritematosas en cara, tronco y extremidades, que no ceden con el uso de Cetirizina en casa.",
        evolucion_ordenes: "Paciente con cuadro de inicio insidioso hace 24 horas, caracterizado por prurito intenso generalizado que progresó a la aparición de lesiones eritematosas maculopapulares en cara, tronco y extremidades. Refiere la madre que no hubo respuesta a la Cetirizina oral administrada en casa, motivando la consulta de emergencia. \n\nAl examen físico: Afebril, eupneico, dolor, quejumbroso, agitado, con prurito intenso, lesiones jabonosas con eritema en todo el cuerpo. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nMedicar con Fendramin EV como antialérgico. \nMedicar con Hidrocortizona EV como antiinflamatorio. \nRevalorar. \n\nNota adicional de manejo: Se administró Adrenalina subcutánea (0.2 cc y 0.1cc IM) debido al aumento del cuadro de inflamación y dificultad para deglutir a pesar del manejo inicial con esteroides.",
    },
    "CAIDA": {
        presentacion: "Paciente de 6 meses de edad, sin antecedentes mórbidos conocidos, es traído vía emergencia por sus padres quienes refieren que dicho paciente estaba estable hasta presentar caída de la cama provocando dolor, irritabilidad, edema y hematoma en región frontal.",
        evolucion_ordenes: "Lactante con historia de caída accidental desde la cama (aproximadamente 50 cm) hace menos de 1 hora, impactando la región frontal. Inició con llanto inmediato, seguido de irritabilidad y la objetivación de edema y hematoma en la zona del impacto, sin pérdida de conocimiento referida. \n\nSe recibe paciente: hipoactivo, eupneico, afebril, mucosa oral seca, saliva espesa, lengua saburral, palidez marcada, debilidad, con dolor, edema y hematoma frontal. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nAdministrar Sinedol Supositorio como analgésico. \nRealizar Radiografía de Cráneo para descartar fractura. \nSe deja bajo observación en Sala Pediátrica con fines de mejoría de cuadro clínico.",
    },
    "CRISIS DE BRONCOESPASMO Y TOS SOLA": {
        presentacion: "Se trata de paciente de 2 años de edad, sin antecedentes mórbidos conocidos, la cual refiere la madre que se encontraba estable hasta hace aproximadamente 24 horas cuando inicia con cuadro de tos seca persistente, que posteriormente se acompañó de marcada dificultad respiratoria expresada en retracciones costales y subcostales.",
        evolucion_ordenes: "Preescolar con cuadro respiratorio agudo de 24 horas de evolución, iniciando con tos seca persistente y progresión a dificultad respiratoria marcada evidenciada por retracciones costales y subcostales, sin fiebre ni otros síntomas asociados inicialmente. \n\nSe recibe paciente: hipoactivo, disneico, presentando congestión nasal, con tiraje intercostal. A la auscultación pulmonar con estertores tipo sibilantes y roncus. \n\nÓrdenes Médicas (Indicaciones): \nMandar a nebulizar paciente con Albuterol más Solución Salina. \nMedicar con Hidrocortizona EV. \nRealizar RX de Tórax para visualización de campo pulmonar y descartar probable proceso infeccioso. \n\nNota adicional de manejo: Se indicó Doblened (por antecedente de asma bronquial) y oxigenoterapia debido a que saturaba aún en 90%.",
    },
    "CRISIS DE BRONCOESPASMO, TOS, RINORREA, VOMITOS": {
        presentacion: "Paciente de 7 meses de edad que estaba estable hasta el día de ayer, cuando comenzó a presentar tos seca persistente de 24 horas de evolución, marcada dificultad respiratoria expresada en retracciones costales y subcostales, acompañada de rinorrea hialina y un vómito de contenido alimenticio.",
        evolucion_ordenes: "Lactante con sintomatología respiratoria y digestiva de 24 horas. Inicia con tos seca persistente, rápidamente progresando a dificultad respiratoria (*tiraje intercostal*), rinorrea hialina y un episodio emético de contenido alimenticio. \n\nSe recibe paciente: hipoactivo, disneico, presentando congestión nasal, con tiraje intercostal. A la auscultación pulmonar con estertores tipo sibilantes y roncus. \n\nÓrdenes Médicas (Indicaciones): \nMandar a nebulizar paciente con Albuterol más Solución Salina. \nMedicar con Hidrocortizona EV. \nRealizar RX de Tórax para visualización de campo pulmonar y descartar probable proceso infeccioso. \nSe deja en observación con fines de mejoría de cuadro clínico.",
    },
    "DIARREA": {
        presentacion: "Se trata de paciente de 6 años de edad, la cual se encontraba estable hasta hace 2 días cuando inició con cuadro de evacuaciones diarreicas, fétidas, amarillentas, de 4-5 deposiciones por día, que luego se acompañó de fiebre alta que no cede a la medicación con Acetaminofén Vía Oral. Presentó más de 10 deposiciones en el día de hoy.",
        evolucion_ordenes: "Escolar con gastroenteritis de 2 días de evolución, inicialmente con 4-5 evacuaciones diarreicas diarias (*fétidas, amarillentas*). El cuadro progresó con la adición de fiebre alta refractaria a antipiréticos orales, y un incremento significativo a >10 deposiciones en las últimas 24 horas, sugiriendo deshidratación. \n\nSe recibe paciente: despierta, hipoactiva, palidez facial, febril, eupneica, con mucosa oral reseca. Amígdalas eutróficas, sin presencia de exudado ni hiperemia. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nMedicar con Paracetamol para contrarrestar temperatura elevada. \nRealizar Hemograma y Coprológico para descartar probable proceso infeccioso.",
    },
    "DIARREA 2": {
        presentacion: "Se trata de paciente de 5 años de edad, con antecedente de Amebiasis (ingresado y dado de alta hace una semana). Hace un día inició con cuadro de fiebre alta que no cede a la medicación con Acetaminofén, y en el día de hoy se acompañaron de evacuaciones diarreicas, fétidas, amarillentas (4 deposiciones), y vómitos de contenido alimenticio (5 ocasiones).",
        evolucion_ordenes: "Preescolar con cuadro de 24 horas de evolución que inició con pico febril alto no controlado con Acetaminofén. Hoy se asocian 4 episodios de diarrea (*fétida, amarillenta*) y 5 episodios eméticos de contenido alimenticio, en un paciente con antecedente reciente de Amebiasis. \n\nSe recibe paciente: hipoactivo, febril, eupneico, con signos de deshidratación (mucosa oral seca, lengua saburral, conjuntivas pálidas). Amígdalas eutróficas. Dolor abdominal difuso a la palpación profunda. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nMedicar con Paracetamol EV para contrarrestar temperatura elevada. \nAdministrar Dramidon EV como antiemético. \nRealizar Hemograma, Coprológico y Examen de Orina para descartar probable proceso infeccioso.",
    },
    "DISMENORREA": {
        presentacion: "Se trata de paciente de 16 años de edad, la cual se encontraba estable hasta hace aproximadamente 3 horas cuando inició con cuadro de dolor pélvico intenso luego de una hora de inicio de la menstruación, que posteriormente se acompañó de vómitos (4 ocasiones de contenido alimenticio) y evacuaciones diarreicas (4 ocasiones).",
        evolucion_ordenes: "Adolescente con cuadro agudo de 3 horas de evolución, desencadenado por el inicio del ciclo menstrual. Presenta dolor pélvico intenso 10/10 tipo cólico, asociado a síntomas gastrointestinales severos: 4 episodios eméticos de contenido alimenticio y 4 evacuaciones diarreicas. \n\nSe recibe paciente: consciente, orientada, afebril, eupneica, palidez facial, con mucosa oral seca. Refiere dolor intenso 10/10 en región pélvica y a la palpación superficial en epigastrio. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nMedicar con Sentrol Compuesto como analgésico para contrarrestar dolor pélvico.",
    },
    "DISNEA, TOS, DIARREA, RINORREA": {
        presentacion: "Se trata de paciente de 7 meses de edad, con antecedente de Asma Bronquial actualmente no tratada. Hace 3 días inició con cuadro de evacuaciones diarreicas, fétidas, amarillentas (4-5 deposiciones por día), que hace un día se acompañó de dificultad respiratoria marcada, aunado a tos persistente y rinorrea.",
        evolucion_ordenes: "Lactante con cuadro mixto de 3 días de evolución. Inicia con diarrea persistente (4-5 deposiciones/día), y hace 24 horas asocia dificultad respiratoria marcada, tos persistente y rinorrea, sugiriendo un proceso infeccioso sistémico o la exacerbación de su asma bronquial de base. \n\nSe recibe paciente: consciente, disneico, hipoactivo, febril, con dificultad respiratoria marcada. Mucosa oral reseca, palidez facial. Amígdalas hipertróficas. A la auscultación pulmonar con estertores tipo sibilantes y roncus. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nMedicar con Paracetamol para contrarrestar temperatura elevada (si aplica). \nNebulizar con Doblened. \nRealizar Hemograma y Coprológico para descartar probable proceso infeccioso.",
    },
    "DOLOR ABDOMINAL": {
        presentacion: "Se trata de paciente de 9 años de edad. Estable hasta hace dos días cuando inicia con cuadro de dolor en epigastrio que empeoró el día de hoy, irradiándose a regiones abdominales bajas, con predominio en hipocondrio derecho y ambos flancos.",
        evolucion_ordenes: "Escolar con dolor abdominal de 48 horas de evolución. Inicialmente epigástrico, con empeoramiento progresivo en las últimas horas e irradiación a hipocondrio derecho y flancos, sin otros síntomas. El dolor es de intensidad considerable. \n\nSe recibe paciente: despierta, orientada, afebril, eupneica. Refiriendo dolor abdominal intenso, difuso, a la palpación profunda, de predominio en epigastrio, hipocondrio derecho y ambos flancos. \n\nÓrdenes Médicas (Indicaciones): \nRealizar Examen de Orina. \nRealizar Sonografía Abdominal para descartar patologías del sistema urinario y/o gastrointestinal.",
    },
    "DOLOR ABDOMINAL (Fiebre y Disuria)": {
        presentacion: "Paciente de 8 años de edad. Estable hasta presentar fiebre no termometrada de dos días de evolución, aunado a náuseas (que no induce al vómito), acompañado de dolor a la palpación superficial y profunda en hipocondrio y flanco izquierdo.",
        evolucion_ordenes: "Escolar con cuadro febril de 2 días de evolución (no cuantificado), asociado a náuseas (sin emesis) y dolor a la palpación en hipocondrio y flanco izquierdo. Refiere disuria, lo que orienta la sospecha diagnóstica hacia el tracto urinario. \n\nSe recibe paciente: consciente, orientado, afebril, eupneico, quejumbroso, hipoactivo, palidez marcada, mucosa oral seca. Presentando dolor a la palpación superficial y profunda en hipocondrio y flanco izquierdo, refiriendo disuria. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nRealizar Hemograma para valorar biometría hemática y descartar proceso infeccioso. \nRealizar Orina para descartar proceso infeccioso de vía urinaria. \nRealizar Sonografía Abdominal para descartar patologías abdominales.",
    },
    "DOLOR LUMBAR": {
        presentacion: "Paciente de 12 años con antecedentes mórbidos conocidos de Falcemia (Anemia de Células Falciformes). Estable hasta el día de hoy cuando inicia un cuadro clínico agudo de dolor lumbar con grado 10/10.",
        evolucion_ordenes: "Adolescente, falcémico conocido, que inicia crisis aguda de dolor lumbar 10/10 de aparición súbita hoy. La intensidad y la localización son altamente sugestivas de una crisis vaso-oclusiva (CVO) a nivel de la columna lumbar. \n\nSe recibe paciente: hipoactivo, eupneico, afebril, mucosa oral seca, saliva espesa, lengua saburral, palidez marcada, debilidad, con dolor y limitación de movimientos en columna lumbar, Puñopercusión positivo. \n\nÓrdenes Médicas (Indicaciones): \nAdministrar Ketorolaco EV como analgésico. \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nSe deja bajo observación en Sala Pediátrica con fines de mejoría de cuadro clínico.",
    },
    "DOLOR PELVICO Y DISURIA": {
        presentacion: "Paciente de 17 años de edad, con embarazo de 7 semanas por US, G4P0C2A1. Estable hasta hace 4 horas cuando inicia dolor pélvico 7/10 tipo cólico acompañado de disuria y náuseas que inducen al vómito (5 ocasiones de contenido alimenticio, luego gástrico).",
        evolucion_ordenes: "Paciente embarazada de 7 semanas con cuadro agudo de 4 horas de evolución. Presenta dolor pélvico 7/10 tipo cólico, asociado a disuria y emesis incoercible (5 episodios), con riesgo de deshidratación y amenaza de aborto. \n\nConsciente, eupneica, afebril, quejumbrosa, mucosa oral seca, lengua saburral, palidez marcada, presentando disuria. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nAdministrar Sertal Simple EV como antiespasmódico. \nRealizar Examen de Orina para descartar infecciones de vías urinarias. \nRealizar Hemograma para valorar biometría hemática y descartar proceso infeccioso. \nRealizar Sonografía Transvaginal para valorar bienestar fetal.",
    },
    "DOLOR PELVICO, SANGRADO VAGINAL TIPO MANCHADO, DISURIA": {
        presentacion: "Paciente de 17 años de edad. Estable hasta hace 4 horas cuando inicia dolor pélvico 8/10 tipo cólico acompañado de disuria y sangrado transvaginal tipo manchado de 3 horas de evolución.",
        evolucion_ordenes: "Paciente femenina con cuadro de 4 horas de evolución. Inicia con dolor pélvico intenso 8/10 tipo cólico, asociado a disuria y sangrado transvaginal tipo manchado de 3 horas. La presentación clínica requiere descartar patología obstétrica o ginecológica aguda. \n\nSe recibe paciente: consciente, orientada, afebril, eupneica, con palidez marcada y mucosa oral seca. Refiere dolor pélvico intenso tipo cólico y sangrado activo. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Lactato de Ringer. \nAdministrar Sertal Simple EV como antiespasmódico. \nRealizar Examen de Orina para descartar infecciones de vías urinarias. \nRealizar Hemograma para valorar biometría hemática y descartar proceso infeccioso.",
    },
    "FIEBRE Y DIARREA (Caso 1)": {
        presentacion: "Paciente de 1 año de edad. Estable hasta hace aproximadamente 2 semanas cuando inició con cuadro de evacuaciones diarreicas, fétidas, amarillentas (4-5 deposiciones por día), que hace un día se acompañó de fiebre alta que no cede a la medicación con Acetaminofén Vía Oral.",
        evolucion_ordenes: "Lactante con diarrea de 2 semanas de evolución (4-5/día), que se complica hace 24 horas con la aparición de fiebre alta refractaria a antipiréticos orales. Se observan signos de infección respiratoria alta en la evaluación. \n\nSe recibe paciente: despierto, hipoactivo, palidez facial, febril, eupneico, con mucosa oral reseca. Amígdalas hipertróficas, con presencia de exudado abundante e hiperemia. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nMedicar con Neomelubrina EV para contrarrestar temperatura elevada. \nRealizar Hemograma y Coprológico para descartar probable proceso infeccioso.",
    },
    "FIEBRE Y DIARREA (Caso 2)": {
        presentacion: "Paciente de 1 año de edad. Estable hasta presentar fiebre no termometrada (ceden y reaparecen con Acetaminofén), aunada a evacuaciones de consistencia líquida, amarillenta, fétida en frecuencia de 8 ocasiones en las últimas 24 horas.",
        evolucion_ordenes: "Lactante con fiebre intermitente que cede parcialmente con Acetaminofén. Hace menos de 24 horas asocia cuadro diarreico agudo con 8 evacuaciones líquidas (*amarillentas, fétidas*), sugiriendo alto riesgo de deshidratación. \n\nPaciente consciente, febril, mucosa oral reseca, lengua saburral, salivación espesa. Amígdalas eutróficas, hiperémicas. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nAdministrar Paracetamol EV como analgésico antipirético. \nRealizar Hemograma para valorar biometría hemática. \nRealizar Coprológico para descartar parasitosis intestinal. \nDejar bajo observación en Sala Pediátrica hasta mejorar cuadro clínico.",
    },
    "FIEBRE Y DIARREA (Caso 3)": {
        presentacion: "Se trata de paciente de 9 años de edad. Estable hasta hace 24 horas cuando inició con cuadro de evacuaciones diarreicas, fétidas, amarillentas (5-6 deposiciones por día), acompañadas de fiebre alta que no cede a la medicación con Acetaminofén Vía Oral.",
        evolucion_ordenes: "Escolar con gastroenteritis de 24 horas de evolución. Se caracteriza por fiebre alta no controlada con manejo oral y 5-6 episodios de diarrea (*fétidas, amarillentas*) en el día. El paciente presenta signos clínicos de deshidratación. \n\nSe recibe paciente: febril, eupneica, con signos de deshidratación (mucosa oral seca, lengua saburral, conjuntivas pálidas). Amígdalas eutróficas, hiperémicas, sin placas. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nIndicar Paracetamol EV para contrarrestar temperatura elevada. \nIndicar Dramidon por hiperémesis. \nRealizar Biometría Hemática y Examen de Orina para descartar probable proceso infeccioso.",
    },
    "FIEBRE Y VOMITO QUE ACUDIO A OTRO CENTRO ANTES": {
        presentacion: "Se trata de paciente de 1 año de edad. Estable hasta hace tres días cuando inició con cuadro de fiebre alta que no cede a la medicación con Acetaminofén Vía Oral, acompañado de vómitos en 5 ocasiones de contenido alimenticio. Acude a este centro por persistencia del cuadro clínico luego de ser tratada y dada de alta en otro centro.",
        evolucion_ordenes: "Lactante con cuadro de 3 días de evolución, iniciado con fiebre alta persistente, asociada a 5 episodios eméticos. Acude por persistencia de la sintomatología a pesar de manejo ambulatorio previo en otro centro, con evidente compromiso del estado de hidratación. \n\nPaciente consciente, quejumbroso, febril. Mucosa oral seca, lengua saburral, conjuntivas pálida, palidez marcada, con signos de deshidratación. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nAdministrar Paracetamol EV como antipirético. \nAdministrar Dramidon EV como antiemético. \nRealizar Hemograma y Orina para descartar proceso infeccioso. \nSe deja bajo observación en Sala Pediátrica con fines de hidratación y mejoría de cuadro clínico.",
    },
    "FIEBRE SOLO": {
        presentacion: "Se trata de paciente de 2 años de edad. Estable hasta hace 24 horas, cuando inició con cuadro de fiebre alta no termometrada, no escalofriante, no convulsivante, que no cede a la medicación con Acetaminofén Vía Oral.",
        evolucion_ordenes: "Preescolar con fiebre aislada de 24 horas de evolución, no controlada con antipiréticos orales. Se evalúa para descartar foco infeccioso, especialmente considerando el compromiso del estado de hidratación. \n\nSe recibe paciente: febril, eupneico, con signos de deshidratación (mucosa oral seca, lengua saburral, conjuntivas pálidas). Amígdalas eutróficas, hiperémicas, con presencia de placas. Pulmones con murmullo vesicular presente. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nIndicar Neomelubrina EV/Paracetamol EV para contrarrestar temperatura elevada. \nRealizar Biometría Hemática y Examen de Orina para descartar probable proceso infeccioso.",
    },
    "FIEBRE, CEFALEA": {
        presentacion: "Se trata de paciente de 10 años de edad. Estable hasta hace tres días cuando inició con cuadro de fiebre alta que no cede a la medicación con antipirético tipo Acetaminofén, acompañado de cefalea holocraneana referida 10/10, y diarrea en tres ocasiones.",
        evolucion_ordenes: "Escolar con cuadro de 3 días de evolución. Inicia con fiebre alta no controlada, a la que se asocia cefalea holocraneana 10/10 y 3 episodios diarreicos. La intensidad de la cefalea requiere atención para descartar patología intracraneal o infección sistémica severa. \n\nSe recibe paciente: consciente, orientada, eupneica, febril, quejumbrosa. Mucosa oral seca, lengua saburral, conjuntivas pálidas, palidez marcada y signos de deshidratación moderada. Amígdalas hipertróficas. \n\nÓrdenes Médicas (Indicaciones): \nHidratar con Solución Salina 0.9%. \nMedicar con Neomelubrina EV como antipirético. \nRealizar Hemograma para valorar biometría hemática y descartar proceso infeccioso. \nRealizar Coprológico para descartar parasitosis. \nDejar en Sala de Observación Pediátrica con fines de hidratación y mejoría de cuadro clínico.",
    },
    "FIEBRE, DEHIDRATACION Y VOMITO DOLOR ABDOMINAL": {
        presentacion: "Se trata de paciente de 6 años de edad. Estable hasta hace tres días cuando inició con cuadro de fiebre alta que no cede a la medicación, acompañado de vómitos en 10 ocasiones de contenido alimenticio, y dolor estomacal de predominio en epigastrio.",
        evolucion_ordenes: "Escolar con sintomatología digestiva y febril de 3 días de evolución. Se caracteriza por fiebre alta no controlada, 10 episodios de vómito incoercible y dolor abdominal intenso de predominio epigástrico, resultando en un cuadro de deshidratación moderada a severa. \n\nPaciente consciente, quejumbroso, febril. Mucosa oral seca, lengua saburral, conjuntivas pálida, palidez marcada. Con dolor abdominal a la palpación superficial y profundo de predominio en epigastrio. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nAdministrar Paracetamol EV como antipirético. \nAdministrar Dramidon EV como antiemético. \nAdministrar Ranitidina EV como protector gástrico. \nRealizar Hemograma para valorar biometría hemática y descartar proceso infeccioso. \nRealizar Orina para descartar infección de vías urinarias. \nSe deja bajo observación en Sala Pediátrica con fines de hidratación y mejoría de cuadro clínico.",
    },
    "FIEBRE, DIARREA, TOS, DISNEA": {
        presentacion: "Se trata de paciente de 4 años de edad. Estable hasta hace aproximadamente 4 días cuando inició con cuadro de evacuaciones diarreicas, fétidas, amarillentas (4-5 deposiciones por día), que luego se acompañó de fiebre alta que no cede a la medicación, tos persistente productiva de secreción blanquecina, y dificultad respiratoria marcada.",
        evolucion_ordenes: "Preescolar con cuadro multisistémico de 4 días de evolución. Inicia con diarrea (4-5/día), progresando a fiebre alta no controlada, tos productiva y dificultad respiratoria marcada (*disnea*), sugiriendo un proceso infeccioso de etiología probablemente viral con compromiso pulmonar. \n\nSe recibe paciente: despierto, hipoactivo, palidez facial, febril, con dificultad respiratoria marcada, tórax hiperdinámico. Mucosa oral reseca. Amígdalas hipertróficas. Dolor abdominal difuso a la palpación profunda. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nMedicar con Paracetamol para contrarrestar temperatura elevada. \nNebulizar con Doblened. \nRealizar Hemograma y Coprológico para descartar probable proceso infeccioso.",
    },
    "FIEBRE, RINORREA, CONGESTION NASAL": {
        presentacion: "Se trata de paciente de 1 año de edad. Estable hasta hace 24 horas, cuando inició con cuadro de fiebre alta que no cede a la medicación con Acetaminofén Vía Oral ni Vía Rectal, acompañado de rinorrea hialina y congestión nasal.",
        evolucion_ordenes: "Lactante con cuadro de infección de vía aérea superior de 24 horas de evolución. Predomina la fiebre alta refractaria a antipiréticos, asociada a rinorrea hialina y congestión nasal. La ausencia de otros síntomas descarta complicaciones sistémicas. \n\nSe recibe paciente: hipoactiva, febril, eupneica, con signos de deshidratación (mucosa oral seca, lengua saburral, conjuntivas pálidas). Amígdalas hipertróficas e hiperémicas, sin exudado, con congestión nasal y rinorrea hialina. Auscultación pulmonar sin estertores presentes. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nIndicar Paracetamol EV para contrarrestar temperatura elevada. \nRealizar Biometría Hemática para descartar probable proceso infeccioso.",
    },
    "FIEBRE, VOMITOS, DIARREA, TOS, DISNEA": {
        presentacion: "Se trata de paciente de 3 años de edad, con antecedentes mórbidos de Asma Bronquial. Estable hasta hace 4 días cuando inició con cuadro de evacuaciones diarreicas (4-5 deposiciones por día) que mejoró, y se aunaron vómitos (3 ocasiones), que luego se acompañaron de fiebre alta, tos persistente, y dificultad respiratoria marcada.",
        evolucion_ordenes: "Preescolar asmático conocido con cuadro complejo de 4 días de evolución. Inicia con diarrea (ya en mejoría), seguida de emesis, fiebre alta, y finalmente tos persistente con disnea marcada, sugiriendo una exacerbación asmática por proceso infeccioso. \n\nPaciente consciente, disneico, quejumbroso, febril. Amígdalas eutróficas e hiperémicas. Murmullo vesicular disminuido, estertores tipo roncus y sibilantes en ambos campos pulmonares, retracciones inter y subcostales. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nMedicar con Paracetamol EV para contrarrestar temperatura elevada. \nAdministrar Dramidon EV como antiemético. \nNebulizar con Doblened. \nRealizar Hemograma y Coprológico para descartar probable proceso infeccioso.",
    },
    "HERIDA": {
        presentacion: "Paciente de 4 años de edad. Estable hasta hace 45 minutos aproximadamente cuando presenta caída de su propio plano de sustento con la patineta mientras jugaba, con pérdida de continuidad de la piel en el mentón de aproximadamente 1 cm.",
        evolucion_ordenes: "Preescolar con trauma facial por caída de su propia altura con patineta hace 45 minutos. Presenta herida lacerada con sangrado activo y pérdida de continuidad de la piel de 1 cm en región del mentón, catalogada como herida potencialmente contaminada. \n\nSe recibe paciente: consciente, irritado, eupneico, quejumbroso, afebril, presentando sangrado y herida en mentón de aproximadamente 1 cm. \n\nÓrdenes Médicas (Indicaciones): \nCurar herida con previa asepsia y antisepsia. \nAdministrar anestesia local con Lidocaína. \nRealizar aproximación de piel con 2 puntos de sutura usando hilo Nylon 5.0. \nCubrir con gasas estériles. \nAdministrar analgésico tipo Diclo-K ped. Supositorio para el dolor. \nAdministrar Gammaglobulina Antitetánica Humana (IGANTET) IM debido a esquema de vacuna incompleto y herida contaminada. \nSe deja bajo observación en Sala Pediátrica con fines de mejoría de cuadro clínico.",
    },
    "INTOXICACIÓN ACCIDENTAL (Por medicamentos)": {
        presentacion: "Paciente de 2 años de edad. Traído por su padre quien encontró al niño con un frasco de pastillas de su abuela (ej. Hipertensivos o hipoglucemiantes) abierto y vaciado parcialmente. El niño está somnoliento y presentó un vómito de contenido desconocido hace 30 minutos.",
        evolucion_ordenes: "Preescolar traído por sospecha de intoxicación accidental por fármacos (*polipíldoras de abuela*) hace 30 minutos. Se evidencia somnolencia progresiva y un episodio emético de contenido desconocido. El riesgo es la absorción sistémica del tóxico y el compromiso hemodinámico/neurológico. \n\nSe recibe paciente: hipoactivo, con tendencia al sueño, afebril, eupneico, con mucosa oral húmeda, pero con olor a sustancia química/medicamento. Signos vitales con bradicardia e hipotensión (dependiendo del tóxico). Al examen físico, no hay signos de trauma. \n\nÓrdenes Médicas (Indicaciones): \nAsegurar y proteger vía aérea (riesgo de aspiración). \nCanalizar con Solución Salina al 0.9% ev y monitorización continua. \nAdministrar Carbón Activado Vía Oral/Sonda Nasogástrica para reducir la absorción (si no hay contraindicaciones). \nRealizar Lavado Gástrico (según el tiempo y el tóxico). \nRealizar Hemograma, Electrolitos, Función Hepática y Renal, Gases Arteriales y Nivel del Tóxico (si es posible). \nTratamiento antídoto específico si se conoce el tóxico. \nTraslado a UCI pediátrica para manejo avanzado.",
    },
    "OTORRAGIA/ODONTALGIA": {
        presentacion: "Se trata de paciente de 12 años de edad. Estable hasta hace dos días cuando inició con cuadro de dolor intenso de oído derecho, que luego se irradia a región maxilar derecha.",
        evolucion_ordenes: "Escolar con dolor en oído derecho de 48 horas de evolución (*otalgia intensa*), con irradiación posterior a la región maxilar ipsilateral. La evaluación revela signos de infección ótica y dental que justifican la sintomatología. \n\nSe recibe paciente: afebril, eupneico, hidratado. Con ausencia de piezas dentales, y presencia de caries en 1er y 2do molar inf. izquierdo y 2do molar inf. derecho. Al examen del oído se observan secreciones blanquecinas en oído externo derecho e izquierdo. Con dolor a la palpación en región retroauricular derecha y región maxilar ipsilateral. \n\nÓrdenes Médicas (Indicaciones): \nProceder a medicar paciente con analgésico tipo Diclofenac (Dioxaflex) IM para el dolor. \nVigilar de cerca.",
    },
    "PICADURA DE TARANTULA (CACATA)": {
        presentacion: "Se trata de paciente de 10 años de edad. Estable, hasta hace aproximadamente 20 minutos cuando sufrió picadura de insecto (presuntamente una tarántula/cacata) de características grande, negra y peluda.",
        evolucion_ordenes: "Escolar con picadura por arácnido (*posible Tarántula/Cacata*) en brazo derecho hace 20 minutos. Presenta síntomas locales (*eritema, edema y secreción*) que requieren monitoreo estricto debido al alto riesgo de reacción anafiláctica/alérgica sistémica. \n\nSe recibe paciente: despierto, activo, afebril, eupneico, hidratado. Presentando picadura de parte distal posterior de brazo derecho, con dos picaduras paralelas. Se observa área de picadura enrojecida, con salida de líquido transparente y ligero hinchazón. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev de 500 cc. \nProceder a medicar con Fendramin EV e Hidrocortisona EV por ser las reacciones alérgicas la principal manifestación de este tipo de picaduras. \nSe procede a despachar estable con tratamiento ambulatorio y seguimiento por el departamento de Epidemiología.",
    },
    "RASH": {
        presentacion: "Se trata de paciente de 12 años de edad, con antecedentes de alergia a colorantes. Hace aprox. 6 días inicia con cuadro de múltiples habones en mejillas, tronco, y extremidades, con edema en región del glande, manos y pies. Acompañado de prurito intenso, que en el día de ayer se aunaron mareos en 2 ocasiones.",
        evolucion_ordenes: "Escolar con antecedente alérgico y urticaria/angioedema de 6 días de evolución, manifestada por múltiples habones y edema en extremidades y glande. El cuadro se complica hace 24 horas con episodios de mareo, sugiriendo una reacción sistémica más severa o un compromiso vascular/metabólico asociado. \n\nSe recibe paciente: despierto, hipoactivo, orientado, conjuntivas pálidas, afebril al momento de la evaluación, con historia de fiebre. Mucosa oral reseca, lengua saburral. Presentando dolor abdominal difuso a la palpación profunda, de predominio en epigastrio, hipocondrio izquierdo e hipogastrio. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nRealizar Hemograma por historia de fiebre de 24 horas. \nIndicar Orina y Coprológico para descartar probable proceso infeccioso.",
    },
    "TRAUMATISMO CRANEOENCEFÁLICO LEVE (TCE)": {
        presentacion: "Paciente de 5 años de edad. Se encontraba jugando y sufrió caída de altura (ej. de un columpio), golpeándose la cabeza contra el suelo. Inicialmente lloró inmediatamente y presentó un solo episodio de vómito de contenido alimenticio minutos después del golpe.",
        evolucion_ordenes: "Preescolar con TCE leve secundario a caída de altura hace minutos. Presenta llanto inmediato y un único episodio emético, sin pérdida de conocimiento prolongada. Requiere vigilancia estricta debido al riesgo de sangrado intracraneal, a pesar de la buena condición inicial. \n\nSe recibe paciente: consciente, alerta, irritable, con llanto fácil. Afebril, eupneica. Se observa hematoma y leve edema en región parietal derecha. No hay pérdida de conocimiento prolongada. Al examen neurológico: pupilas isocóricas, reactivas. No hay signos de focalización. \n\nÓrdenes Médicas (Indicaciones): \nReposo absoluto en Sala de Observación Pediátrica. \nAplicar hielo local en la zona del trauma. \nAdministrar Acetaminofén/Ibuprofeno si el dolor lo requiere. \nDieta líquida inicial y progresión. \nObservación estricta (Escala de Glasgow y vigilancia neurológica) por 4-6 horas. \nRealizar TAC de cráneo solo si el vómito es persistente, hay cefalea intensa o el estado de conciencia se deteriora. \nAlta con signos de alarma claros a los padres si la evolución es satisfactoria.",
    },
    "VOMITOS POR CONTENIDO ALIMENTICIO": {
        presentacion: "Se trata de paciente de 1 año de edad. Estable hasta presentar vómitos de contenidos alimentarios, no bilioso, no hemático, en 4 ocasiones de 30 minutos de evolución luego de haber ingerido una vitamina.",
        evolucion_ordenes: "Lactante con emesis de inicio agudo hace 30 minutos (4 episodios) de contenido alimenticio, no bilioso ni hemático, posterior a la ingesta de una vitamina. El paciente presenta signos de deshidratación leve por la emesis. \n\nSe recibe paciente: consciente, quejumbroso, afebril. Mucosa oral seca, lengua saburral, conjuntivas pálida, palidez marcada. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nAdministrar Dramidon EV como antiemético. \nSe deja bajo observación en Sala Pediátrica con fines de hidratación y mejoría de cuadro clínico.",
    },
    "CONVULSIÓN FEBRIL": {
        presentacion: "Se trata de paciente de 3 años de edad, con antecedente de convulsiones febriles previas (hace 6 meses), el cual se encontraba estable hasta hace 1 hora cuando inició con cuadro de fiebre alta no termometrada. Minutos después, presenta episodio tónico-clónico generalizado de aproximadamente 3 minutos de duración, con pérdida del conocimiento.",
        evolucion_ordenes: "Preescolar con antecedente de convulsión febril previa, que presenta pico febril hace 1 hora seguido de episodio tónico-clónico generalizado de 3 minutos de duración con pérdida del conocimiento. Se maneja como convulsión febril compleja, requiriendo estabilización y búsqueda de foco infeccioso. \n\nSe recibe paciente: post-crisis, somnoliento, afebril (tras administración de antipirético rectal por los padres), con mucosa oral seca, palidez marcada. Eupneico. Al examen neurológico: respuesta lenta a estímulos verbales. Signos vitales estables, salvo por ligera taquicardia. \n\nÓrdenes Médicas (Indicaciones): \nAsegurar vía aérea y colocar en decúbito lateral. \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable. \nAdministrar Diazepam EV si el paciente vuelve a convulsionar (indicación de rescate). \nAdministrar Paracetamol EV para control térmico. \nRealizar Hemograma, Electrolitos y Glicemia para descartar causas metabólicas/infecciosas. \nObservación estricta en Sala de Emergencia Pediátrica por al menos 12 horas.",
    },
    "CUERPO EXTRAÑO EN VÍA AÉREA / ASFIXIA (Atoramiento)": {
        presentacion: "Paciente de 1 año de edad, sin antecedentes mórbidos. Es traída por su madre quien refiere que la paciente se encontraba jugando con una pelota pequeña hace 15 minutos e inicia súbitamente con dificultad respiratoria marcada, cianosis perioral y tos inefectiva.",
        evolucion_ordenes: "Lactante con obstrucción aguda de vía aérea (*cuerpo extraño - pelota pequeña*) hace 15 minutos. Inicia súbitamente con dificultad respiratoria marcada, cianosis perioral y tos inefectiva, siendo una emergencia vital. \n\nSe recibe paciente: disneica, con cianosis perioral evidente, agitada, con estridor audible y tos débil. A la auscultación pulmonar, se encuentra disminución marcada o ausencia del murmullo vesicular en un hemitórax. El paciente presenta signos de agotamiento. \n\nÓrdenes Médicas (Indicaciones): \nManiobra de Heimlich/Palmadas en espalda (según edad) inmediata para intentar desalojar el cuerpo extraño. \nAdministrar Oxígeno por mascarilla con reservorio (si el cuerpo extraño se desalojó parcialmente). \nLaringoscopía/Broncoscopía de emergencia si la maniobra inicial falla y el estado del paciente lo permite. \nRealizar RX de Tórax y Cuello para localizar el objeto (si está estable). \nMantener en observación en UCI pediátrica para vigilar complicaciones.",
    },
    "DIAGNOSTICO NO INCLUIDO EN DATA": {
        presentacion: "Se trata de paciente. Los detalles de la Presentación no están incluidos en el historial.",
        evolucion_ordenes: "Se recibe paciente. La Evolución no está detallada en el historial. \n\nÓrdenes Médicas (Indicaciones): \nPendiente de órdenes médicas. \nCanalizar con Solución Salina al 0.9% ev y mantener vía permeable."
    }
};
