const dataInformes = {
    "ALERGIAS": {
        presentacion: "Sin antecedentes mórbidos, se encontraba asintomático hasta el día de ayer, cuando comenzó con prurito intenso generalizado y lesiones eritematosas en cara, tronco y extremidades, que no ceden con el uso de Cetirizina en casa.",
        evolucion_ordenes: "Al examen físico: Afebril, eupneico, adolorido, quejumbroso, agitado, con prurito intenso y lesiones jabonosas con eritema en todo el cuerpo. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nMedicar con Fendramin EV como antialérgico. \nMedicar con Hidrocortisona EV como antiinflamatorio. \nRevalorar. \n\nNota adicional de manejo: Se administró Adrenalina subcutánea (0.2 cc y 0.1cc IM) debido al aumento del cuadro de inflamación y dificultad para deglutir, a pesar del manejo inicial con esteroides.",
    },
    "CAIDA": {
        presentacion: "Sin antecedentes mórbidos conocidos, se encontraba estable hasta presentar caída de la cama, provocando dolor, irritabilidad, edema y hematoma en la región frontal.",
        evolucion_ordenes: "Se recibe hipoactivo, eupneico, afebril, con mucosa oral seca, saliva espesa, lengua saburral, palidez marcada, debilidad, dolor, edema y hematoma frontal. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nAdministrar Sinedol Supositorio como analgésico. \nRealizar Radiografía de Cráneo para descartar fractura. \nDejar bajo observación en Sala Pediátrica con fines de mejorar el cuadro clínico.",
    },
    "CRISIS DE BRONCOESPASMO Y TOS SOLA": {
        presentacion: "Sin antecedentes mórbidos conocidos. Refiere la madre que se encontraba estable hasta hace aproximadamente 24 horas, cuando comenzó con tos seca persistente, que luego se acompañó de marcada dificultad respiratoria expresada en retracciones costales y subcostales.",
        evolucion_ordenes: "Se recibe hipoactivo, disneico, con congestión nasal y tiraje intercostal. A la auscultación pulmonar, se encuentran estertores tipo sibilantes y roncus. \n\nÓrdenes Médicas (Indicaciones): \nIndicar nebulización con Albuterol más Solución Salina. \nMedicar con Hidrocortisona EV. \nRealizar RX de Tórax para valorar el campo pulmonar y descartar un proceso infeccioso. \n\nNota adicional de manejo: Se indicó Doblened (por antecedente de asma bronquial) y oxigenoterapia debido a que aún saturaba en 90%.",
    },
    "CRISIS DE BRONCOESPASMO, TOS, RINORREA, VOMITOS": {
        presentacion: "Estable hasta el día de ayer, cuando comenzó con tos seca persistente de 24 horas de evolución, marcada dificultad respiratoria expresada en retracciones costales y subcostales, acompañada de rinorrea hialina y un episodio de vómito alimenticio.",
        evolucion_ordenes: "Se recibe hipoactivo, disneico, con congestión nasal y tiraje intercostal. A la auscultación pulmonar, se encuentran estertores tipo sibilantes y roncus. \n\nÓrdenes Médicas (Indicaciones): \nIndicar nebulización con Albuterol más Solución Salina. \nMedicar con Hidrocortisona EV. \nRealizar RX de Tórax para valorar el campo pulmonar y descartar un proceso infeccioso. \nDejar en observación con fines de mejorar el cuadro clínico.",
    },
    "DIARREA": {
        presentacion: "Se encontraba estable hasta hace 2 días, cuando comenzó con evacuaciones diarreicas, fétidas, amarillentas (4-5 deposiciones por día), que luego se acompañaron de fiebre alta que no cede al Acetaminofén oral. Presentó más de 10 deposiciones en el día de hoy.",
        evolucion_ordenes: "Se recibe despierta, hipoactiva, con palidez facial, febril, eupneica y mucosa oral reseca. Amígdalas eutróficas, sin exudado ni hiperemia. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nMedicar con Paracetamol para controlar la fiebre. \nRealizar Hemograma y Coprológico para descartar un proceso infeccioso.",
    },
    "DIARREA 2": {
        presentacion: "Con antecedente de Amebiasis (ingresado y dado de alta hace una semana). Hace un día comenzó con fiebre alta que no cede al Acetaminofén, y hoy se acompañó de evacuaciones diarreicas, fétidas, amarillentas (4 deposiciones), y vómitos alimenticios (5 ocasiones).",
        evolucion_ordenes: "Se recibe hipoactivo, febril, eupneico, con signos de deshidratación (mucosa oral seca, lengua saburral, conjuntivas pálidas). Amígdalas eutróficas. Dolor abdominal difuso a la palpación profunda. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nMedicar con Paracetamol EV para controlar la fiebre. \nAdministrar Dramidon EV como antiemético. \nRealizar Hemograma, Coprológico y Examen de Orina para descartar un proceso infeccioso.",
    },
    "DISMENORREA": {
        presentacion: "Se encontraba estable hasta hace aproximadamente 3 horas, cuando comenzó con dolor pélvico intenso una hora después del inicio de la menstruación, que posteriormente se acompañó de vómitos (4 episodios alimenticios) y evacuaciones diarreicas (4 episodios).",
        evolucion_ordenes: "Se recibe consciente, orientada, afebril, eupneica, con palidez facial y mucosa oral seca. Refiere dolor intenso 10/10 en región pélvica y a la palpación superficial en epigastrio. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nMedicar con Sentrol Compuesto como analgésico para aliviar el dolor pélvico.",
    },
    "DISNEA, TOS, DIARREA, RINORREA": {
        presentacion: "Con antecedente de Asma Bronquial actualmente no tratada. Hace 3 días comenzó con evacuaciones diarreicas, fétidas, amarillentas (4-5 deposiciones por día), que hace un día se acompañó de dificultad respiratoria marcada, además de tos persistente y rinorrea.",
        evolucion_ordenes: "Se recibe consciente, disneico, hipoactivo, febril, con dificultad respiratoria marcada. Mucosa oral reseca, palidez facial. Amígdalas hipertróficas. A la auscultación pulmonar, se encuentran estertores tipo sibilantes y roncus. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nMedicar con Paracetamol para controlar la fiebre (si aplica). \nNebulizar con Doblened. \nRealizar Hemograma y Coprológico para descartar un proceso infeccioso.",
    },
    "DOLOR ABDOMINAL": {
        presentacion: "Estable hasta hace dos días, cuando comenzó con dolor en epigastrio que empeoró hoy, irradiándose a regiones abdominales bajas, con predominio en hipocondrio derecho y ambos flancos.",
        evolucion_ordenes: "Se recibe despierta, orientada, afebril, eupneica. Refiere dolor abdominal intenso, difuso, a la palpación profunda, de predominio en epigastrio, hipocondrio derecho y ambos flancos. \n\nÓrdenes Médicas (Indicaciones): \nRealizar Examen de Orina. \nRealizar Sonografía Abdominal para descartar patologías del sistema urinario o gastrointestinal.",
    },
    "DOLOR ABDOMINAL (Fiebre y Disuria)": {
        presentacion: "Estable hasta presentar fiebre no termometrada de dos días de evolución, además de náuseas (sin vómito), y dolor a la palpación superficial y profunda en hipocondrio y flanco izquierdo.",
        evolucion_ordenes: "Se recibe consciente, orientado, afebril, eupneico, quejumbroso, hipoactivo, con palidez marcada y mucosa oral seca. Presenta dolor a la palpación superficial y profunda en hipocondrio y flanco izquierdo, refiriendo disuria. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nRealizar Hemograma para valorar la biometría hemática y descartar un proceso infeccioso. \nRealizar Examen de Orina para descartar una infección urinaria. \nRealizar Sonografía Abdominal para descartar patologías abdominales.",
    },
    "DOLOR LUMBAR": {
        presentacion: "Con antecedentes mórbidos conocidos de Falcemia (Anemia de Células Falciformes). Estable hasta el día de hoy, cuando comenzó con un cuadro clínico agudo de dolor lumbar con grado 10/10.",
        evolucion_ordenes: "Se recibe hipoactivo, eupneico, afebril, con mucosa oral seca, saliva espesa, lengua saburral, palidez marcada, debilidad, dolor y limitación de movimientos en columna lumbar. Puñopercusión positivo. \n\nÓrdenes Médicas (Indicaciones): \nAdministrar Ketorolaco EV como analgésico. \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nDejar bajo observación en Sala Pediátrica con fines de mejorar el cuadro clínico.",
    },
    "DOLOR PELVICO Y DISURIA": {
        presentacion: "Con embarazo de 7 semanas por US, G4P0C2A1. Estable hasta hace 4 horas, cuando comenzó con dolor pélvico 7/10 tipo cólico, acompañado de disuria y náuseas que indujeron al vómito (5 episodios: contenido alimenticio, luego gástrico).",
        evolucion_ordenes: "Se recibe consciente, eupneica, afebril, quejumbrosa, con mucosa oral seca, lengua saburral y palidez marcada. Presenta disuria. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nAdministrar Sertal Simple EV como antiespasmódico. \nRealizar Examen de Orina para descartar infección urinaria. \nRealizar Hemograma para valorar la biometría hemática y descartar un proceso infeccioso. \nRealizar Sonografía Transvaginal para valorar el bienestar fetal.",
    },
    "DOLOR PELVICO, SANGRADO VAGINAL TIPO MANCHADO, DISURIA": {
        presentacion: "Estable hasta hace 4 horas, cuando comenzó con dolor pélvico 8/10 tipo cólico, acompañado de disuria y sangrado transvaginal tipo manchado de 3 horas de evolución.",
        evolucion_ordenes: "Se recibe consciente, orientada, afebril, eupneica, con palidez marcada y mucosa oral seca. Refiere dolor pélvico intenso tipo cólico y sangrado activo. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Lactato de Ringer. \nAdministrar Sertal Simple EV como antiespasmódico. \nRealizar Examen de Orina para descartar infección urinaria. \nRealizar Hemograma para valorar la biometría hemática y descartar un proceso infeccioso.",
    },
    "FIEBRE Y DIARREA (Caso 1)": {
        presentacion: "Estable hasta hace aproximadamente 2 semanas, cuando comenzó con evacuaciones diarreicas, fétidas, amarillentas (4-5 deposiciones por día), que hace un día se acompañaron de fiebre alta que no cede al Acetaminofén oral.",
        evolucion_ordenes: "Se recibe despierto, hipoactivo, con palidez facial, febril, eupneico y mucosa oral reseca. Amígdalas hipertróficas, con abundante exudado e hiperemia. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nMedicar con Neomelubrina EV para controlar la fiebre. \nRealizar Hemograma y Coprológico para descartar un proceso infeccioso.",
    },
    "FIEBRE Y DIARREA (Caso 2)": {
        presentacion: "Estable hasta presentar fiebre no termometrada (cede y reaparece con Acetaminofén), además de evacuaciones de consistencia líquida, amarillenta, fétida, en 8 ocasiones en las últimas 24 horas.",
        evolucion_ordenes: "Se recibe consciente, febril, con mucosa oral reseca, lengua saburral y salivación espesa. Amígdalas eutróficas, hiperémicas. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nAdministrar Paracetamol EV como analgésico antipirético. \nRealizar Hemograma para valorar la biometría hemática. \nRealizar Coprológico para descartar parasitosis intestinal. \nDejar bajo observación en Sala Pediátrica hasta mejorar el cuadro clínico.",
    },
    "FIEBRE Y DIARREA (Caso 3)": {
        presentacion: "Estable hasta hace 24 horas, cuando comenzó con evacuaciones diarreicas, fétidas, amarillentas (5-6 deposiciones por día), acompañadas de fiebre alta que no cede al Acetaminofén oral.",
        evolucion_ordenes: "Se recibe febril, eupneica, con signos de deshidratación (mucosa oral seca, lengua saburral, conjuntivas pálidas). Amígdalas eutróficas, hiperémicas, sin placas. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nIndicar Paracetamol EV para controlar la fiebre. \nIndicar Dramidon por hiperémesis. \nRealizar Biometría Hemática y Examen de Orina para descartar un proceso infeccioso.",
    },
    "FIEBRE Y VOMITO QUE ACUDIO A OTRO CENTRO ANTES": {
        presentacion: "Estable hasta hace tres días, cuando comenzó con fiebre alta que no cede al Acetaminofén oral, acompañado de 5 episodios de vómito alimenticio. Acude a este centro por persistencia del cuadro clínico tras ser dado/a de alta en otro centro.",
        evolucion_ordenes: "Se recibe consciente, quejumbroso, febril, con signos de deshidratación (mucosa oral seca, lengua saburral, conjuntivas pálidas y palidez marcada). \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nAdministrar Paracetamol EV como antipirético. \nAdministrar Dramidon EV como antiemético. \nRealizar Hemograma y Orina para descartar un proceso infeccioso. \nDejar bajo observación en Sala Pediátrica con fines de hidratación y mejorar el cuadro clínico.",
    },
    "FIEBRE SOLO": {
        presentacion: "Estable hasta hace 24 horas, cuando comenzó con fiebre alta no termometrada, no escalofriante, no convulsivante, que no cede al Acetaminofén oral.",
        evolucion_ordenes: "Se recibe febril, eupneico, con signos de deshidratación (mucosa oral seca, lengua saburral, conjuntivas pálidas). Amígdalas eutróficas, hiperémicas, con placas. Pulmones con murmullo vesicular presente. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nIndicar Neomelubrina EV/Paracetamol EV para controlar la fiebre. \nRealizar Biometría Hemática y Examen de Orina para descartar un proceso infeccioso.",
    },
    "FIEBRE, CEFALEA": {
        presentacion: "Estable hasta hace tres días, cuando comenzó con fiebre alta que no cede al antipirético tipo Acetaminofén, acompañado de cefalea holocraneana referida 10/10 y diarrea en tres ocasiones.",
        evolucion_ordenes: "Se recibe consciente, orientada, eupneica, febril, quejumbrosa, con palidez marcada, mucosa oral seca, lengua saburral y conjuntivas pálidas. Signos de deshidratación moderada. Amígdalas hipertróficas. \n\nÓrdenes Médicas (Indicaciones): \nHidratar con Solución Salina 0.9%. \nMedicar con Neomelubrina EV como antipirético. \nRealizar Hemograma para valorar la biometría hemática y descartar un proceso infeccioso. \nRealizar Coprológico para descartar parasitosis. \nDejar en Sala de Observación Pediátrica con fines de hidratación y mejorar el cuadro clínico.",
    },
    "FIEBRE, DEHIDRATACION Y VOMITO DOLOR ABDOMINAL": {
        presentacion: "Estable hasta hace tres días, cuando comenzó con fiebre alta que no cede a la medicación, acompañado de 10 episodios de vómito alimenticio y dolor estomacal de predominio en epigastrio.",
        evolucion_ordenes: "Se recibe consciente, quejumbroso, febril, con palidez marcada, mucosa oral seca, lengua saburral y conjuntivas pálidas. Dolor abdominal a la palpación superficial y profunda de predominio en epigastrio. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nAdministrar Paracetamol EV como antipirético. \nAdministrar Dramidon EV como antiemético. \nAdministrar Ranitidina EV como protector gástrico. \nRealizar Hemograma para valorar la biometría hemática y descartar un proceso infeccioso. \nRealizar Examen de Orina para descartar infección urinaria. \nDejar bajo observación en Sala Pediátrica con fines de hidratación y mejorar el cuadro clínico.",
    },
    "FIEBRE, DIARREA, TOS, DISNEA": {
        presentacion: "Estable hasta hace aproximadamente 4 días, cuando comenzó con evacuaciones diarreicas, fétidas, amarillentas (4-5 deposiciones por día), que luego se acompañaron de fiebre alta que no cede a la medicación, tos persistente productiva de secreción blanquecina y dificultad respiratoria marcada.",
        evolucion_ordenes: "Se recibe despierto, hipoactivo, con palidez facial, febril, dificultad respiratoria marcada y tórax hiperdinámico. Mucosa oral reseca. Amígdalas hipertróficas. Dolor abdominal difuso a la palpación profunda. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nMedicar con Paracetamol para controlar la fiebre. \nNebulizar con Doblened. \nRealizar Hemograma y Coprológico para descartar un proceso infeccioso.",
    },
    "FIEBRE, RINORREA, CONGESTION NASAL": {
        presentacion: "Estable hasta hace 24 horas, cuando comenzó con fiebre alta que no cede al Acetaminofén oral ni rectal, acompañado de rinorrea hialina y congestión nasal.",
        evolucion_ordenes: "Se recibe hipoactivo, febril, eupneico, con signos de deshidratación (mucosa oral seca, lengua saburral, conjuntivas pálidas). Amígdalas hipertróficas e hiperémicas, sin exudado, con congestión nasal y rinorrea hialina. Auscultación pulmonar sin estertores. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nIndicar Paracetamol EV para controlar la fiebre. \nRealizar Biometría Hemática para descartar un proceso infeccioso.",
    },
    "FIEBRE, VOMITOS, DIARREA, TOS, DISNEA": {
        presentacion: "Con antecedentes mórbidos de Asma Bronquial. Estable hasta hace 4 días, cuando comenzó con evacuaciones diarreicas (4-5 deposiciones por día) que mejoraron, y se agregaron 3 episodios de vómito. Luego se acompañó de fiebre alta, tos persistente y dificultad respiratoria marcada.",
        evolucion_ordenes: "Se recibe consciente, disneico, quejumbroso, febril. Amígdalas eutróficas e hiperémicas. Murmullo vesicular disminuido, con estertores tipo roncus y sibilantes en ambos campos pulmonares, y retracciones inter y subcostales. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nMedicar con Paracetamol EV para controlar la fiebre. \nAdministrar Dramidon EV como antiemético. \nNebulizar con Doblened. \nRealizar Hemograma y Coprológico para descartar un proceso infeccioso.",
    },
    "HERIDA": {
        presentacion: "Estable hasta hace aproximadamente 45 minutos, cuando sufrió caída de su propio plano de sustento con la patineta mientras jugaba, resultando en una herida en el mentón de 1 cm aproximadamente.",
        evolucion_ordenes: "Se recibe consciente, irritado, eupneico, quejumbroso, afebril, con sangrado y una herida en el mentón de 1 cm aproximadamente. \n\nÓrdenes Médicas (Indicaciones): \nRealizar curación con asepsia y antisepsia. \nAdministrar anestesia local con Lidocaína. \nRealizar aproximación de piel con 2 puntos de sutura usando hilo Nylon 5.0. \nCubrir con gasas estériles. \nAdministrar analgésico tipo Diclo-K ped. Supositorio para el dolor. \nAdministrar Gammaglobulina Antitetánica Humana (IGANTET) IM debido al esquema de vacunación incompleto y herida contaminada. \nDejar bajo observación en Sala Pediátrica con fines de mejorar el cuadro clínico.",
    },
    "INTOXICACIÓN ACCIDENTAL (Por medicamentos)": {
        presentacion: "Traído por su padre, quien encontró al paciente con un frasco de pastillas de su abuela (ej. Hipertensivos o hipoglucemiantes) abierto y vaciado parcialmente. Se encuentra somnoliento y presentó un episodio de vómito de contenido desconocido hace 30 minutos.",
        evolucion_ordenes: "Se recibe hipoactivo, con tendencia al sueño, afebril, eupneico, con mucosa oral húmeda, pero con olor a sustancia química/medicamento. Signos vitales con bradicardia e hipotensión (dependiendo del tóxico). Al examen físico, no hay signos de trauma. \n\nÓrdenes Médicas (Indicaciones): \nAsegurar y proteger la vía aérea (riesgo de aspiración). \nCanalizar con Solución Salina al 0.9% y monitorización continua. \nAdministrar Carbón Activado Vía Oral/Sonda Nasogástrica para reducir la absorción (si no hay contraindicaciones). \nRealizar Lavado Gástrico (según el tiempo y el tóxico). \nRealizar Hemograma, Electrolitos, Función Hepática y Renal, Gases Arteriales y Nivel del Tóxico (si es posible). \nIndicar tratamiento antídoto específico si se conoce el tóxico. \nTraslado a UCI pediátrica para manejo avanzado.",
    },
    "OTORRAGIA/ODONTALGIA": {
        presentacion: "Estable hasta hace dos días, cuando comenzó con dolor intenso de oído derecho, que luego se irradia a la región maxilar derecha.",
        evolucion_ordenes: "Se recibe afebril, eupneico, hidratado. Con ausencia de piezas dentales y presencia de caries en 1er y 2do molar inferior izquierdo y 2do molar inferior derecho. Al examen del oído, se observan secreciones blanquecinas en oído externo derecho e izquierdo. Dolor a la palpación en región retroauricular derecha y región maxilar ipsilateral. \n\nÓrdenes Médicas (Indicaciones): \nProceder a medicar con analgésico tipo Diclofenac (Dioxaflex) IM para el dolor. \nVigilar de cerca.",
    },
    "PICADURA DE TARANTULA (CACATA)": {
        presentacion: "Estable hasta hace aproximadamente 20 minutos, cuando sufrió picadura de insecto (presuntamente una tarántula/cacata) de características grande, negra y peluda.",
        evolucion_ordenes: "Se recibe despierto, activo, afebril, eupneico, hidratado. Presenta picadura en la parte distal posterior del brazo derecho, con dos punciones paralelas. Se observa el área de picadura enrojecida, con salida de líquido transparente y ligera hinchazón. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% de 500 cc. \nMedicar con Fendramin EV e Hidrocortisona EV por ser las reacciones alérgicas la principal manifestación de este tipo de picaduras. \nSe procede a dar de alta estable, con tratamiento ambulatorio y seguimiento por el departamento de Epidemiología.",
    },
    "RASH": {
        presentacion: "Con antecedentes de alergia a colorantes. Hace aprox. 6 días comenzó con múltiples habones en mejillas, tronco y extremidades, con edema en la región del glande, manos y pies. Acompañado de prurito intenso, y en el día de ayer se agregaron 2 episodios de mareos.",
        evolucion_ordenes: "Se recibe despierto, hipoactivo, orientado, con conjuntivas pálidas, afebril al momento de la evaluación, con historia de fiebre. Mucosa oral reseca, lengua saburral. Presenta dolor abdominal difuso a la palpación profunda, de predominio en epigastrio, hipocondrio izquierdo e hipogastrio. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nRealizar Hemograma por historia de fiebre de 24 horas. \nIndicar Examen de Orina y Coprológico para descartar un proceso infeccioso.",
    },
    "TRAUMATISMO CRANEOENCEFÁLICO LEVE (TCE)": {
        presentacion: "Se encontraba jugando y sufrió caída de altura (ej. de un columpio), golpeándose la cabeza contra el suelo. Inicialmente lloró de inmediato y presentó un solo episodio de vómito alimenticio minutos después del golpe.",
        evolucion_ordenes: "Se recibe consciente, alerta, irritable, con llanto fácil. Afebril, eupneica. Se observa hematoma y leve edema en la región parietal derecha. No hay pérdida de conocimiento prolongada. Al examen neurológico: pupilas isocóricas, reactivas. No hay signos de focalización. \n\nÓrdenes Médicas (Indicaciones): \nReposo absoluto en Sala de Observación Pediátrica. \nAplicar hielo local en la zona del trauma. \nAdministrar Acetaminofén/Ibuprofeno si el dolor lo requiere. \nDieta líquida inicial y progresión. \nObservación estricta (Escala de Glasgow y vigilancia neurológica) por 4-6 horas. \nRealizar TAC de cráneo solo si el vómito es persistente, hay cefalea intensa o el estado de conciencia se deteriora. \nAlta con signos de alarma claros a los padres si la evolución es satisfactoria.",
    },
    "VOMITOS POR CONTENIDO ALIMENTICIO": {
        presentacion: "Estable hasta presentar 4 episodios de vómito alimenticio (no bilioso, no hemático) de 30 minutos de evolución, luego de haber ingerido una vitamina.",
        evolucion_ordenes: "Se recibe consciente, quejumbroso, afebril, con palidez marcada, mucosa oral seca, lengua saburral y conjuntivas pálidas. \n\nÓrdenes Médicas (Indicaciones): \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nAdministrar Dramidon EV como antiemético. \nDejar bajo observación en Sala Pediátrica con fines de hidratación y mejorar el cuadro clínico.",
    },
    "CONVULSIÓN FEBRIL": {
        presentacion: "Con antecedente de convulsiones febriles previas (hace 6 meses). Se encontraba estable hasta hace 1 hora, cuando comenzó con fiebre alta no termometrada. Minutos después, presenta episodio tónico-clónico generalizado de 3 minutos de duración aproximadamente, con pérdida del conocimiento.",
        evolucion_ordenes: "Se recibe post-crisis, somnoliento, afebril (tras administración de antipirético rectal por los padres), con mucosa oral seca y palidez marcada. Eupneico. Al examen neurológico: respuesta lenta a estímulos verbales. Signos vitales estables, salvo por ligera taquicardia. \n\nÓrdenes Médicas (Indicaciones): \nAsegurar la vía aérea y colocar en decúbito lateral. \nCanalizar con Solución Salina al 0.9% y mantener vía permeable. \nAdministrar Diazepam EV si vuelve a convulsionar (indicación de rescate). \nAdministrar Paracetamol EV para control térmico. \nRealizar Hemograma, Electrolitos y Glicemia para descartar causas metabólicas o infecciosas. \nObservación estricta en Sala de Emergencia Pediátrica por al menos 12 horas.",
    },
    "CUERPO EXTRAÑO EN VÍA AÉREA / ASFIXIA (Atoramiento)": {
        presentacion: "Sin antecedentes mórbidos. Es traído por su madre, quien refiere que se encontraba jugando con una pelota pequeña hace 15 minutos y comenzó súbitamente con dificultad respiratoria marcada, cianosis perioral y tos inefectiva.",
        evolucion_ordenes: "Se recibe disneico, con cianosis perioral evidente, agitado, con estridor audible y tos débil. A la auscultación pulmonar, se encuentra disminución marcada o ausencia del murmullo vesicular en un hemitórax. Presenta signos de agotamiento. \n\nÓrdenes Médicas (Indicaciones): \nManiobra de Heimlich/Palmadas en espalda (según edad) inmediata para intentar desalojar el cuerpo extraño. \nAdministrar Oxígeno por mascarilla con reservorio (si el cuerpo extraño se desalojó parcialmente). \nLaringoscopía/Broncoscopía de emergencia si la maniobra inicial falla y el estado del paciente lo permite. \nRealizar RX de Tórax y Cuello para localizar el objeto (si está estable). \nMantener en observación en UCI pediátrica para vigilar complicaciones.",
    },
    "DIAGNOSTICO NO INCLUIDO EN DATA": {
        presentacion: "Los detalles de la Presentación no están incluidos en el historial.",
        evolucion_ordenes: "La Evolución no está detallada en el historial. \n\nÓrdenes Médicas (Indicaciones): \nPendiente de órdenes médicas. \nCanalizar con Solución Salina al 0.9% y mantener vía permeable."
    }
};